dist: trusty
sudo: required
language: cpp
compiler: gcc
# install:
#   - |
#     if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
#       if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
#         CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
#         mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
#       fi
#       export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
#     fi
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      # SDL libraries
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-ttf-dev
      - libsdl2-mixer-dev
script:
  # Link gcc-6 and g++-6 to their standard commands
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Give all access rights to all files for an easier time
  - sudo chmod -R 777 *
  - ./travis.sh
notifications:
  email: false
  slack:
    secure: EOCD5zvp2C3VURtEGAauoqIwq8hHkOnz/AMBHc08X+NoANuCzjPQbVVWorW1nu/Xz4p1sHtmKY7IbTXv4TxGVLVIav4iABq39UNXmndrN0ThnSExI3mD3Iw/jRAZQDw45SoWQ3mxwUksq6PtyHnT3O9YAcKJsOxm65DLBCQpbYYxCukfaKHkqddf91oq4A4V3H8u1DD0e9ZVNJlOx1ImI4+NtHP4CdK2RyyeE/6tx6mAOfjBmh8bY1TNd3nBPAjevvB4IzwConkjMcbjR3gWRugK5Z1fEHk7cWQ95DYxYmwCdvoqsPagixhdCfQZg4K0i1Vhiz88rDAolI1eu0ehikAY8RBrC6fL3PxWfp6Drcla1v9ng1/e80okzsj4Nw/wC7+A8uii90KEfTgCEBCeLj9DsOjm/t6Keeafe1TmsVy90sUEADXvmyE99lBrXKCIZ9CL/YXm11+YNZJBWkH5U50iO8MeNVF/raCac7tuu0LxBML8lxG1La3/uPUhSDDlJkKEDGgE8Y8a6T2/Npnpx04Q7JtP3ChH0OkcFG8c2zuZ5xb9YadRtsTEQ4hBZ2m9p8UWR7TlKnB5BtIs6ehReT6io69qrlm9AiFLJrQtE6Faq1/TIGs4MULmoVgvstE++cS+Z1MVX3eB1IFQWO5P3OE6Oe3BIcQ36VbGR3VgoAw=
